export const START_LOAD_RUNTIME = 'START_LOAD_RUNTIME';
export const FINISH_LOAD_RUNTIME = 'FINISH_LOAD_RUNTIME';
export const FAIL_LOAD_RUNTIME = 'FAIL_LOAD_RUNTIME';

export const START_PARSE = 'START_PARSE';
export const FINISH_PARSE = 'FINISH_PARSE';
export const FAIL_PARSE = 'FAIL_PARSE';

export const START_COMPILE = 'START_COMPILE';
export const FINISH_COMPILE = 'FINISH_COMPILE';
export const FAIL_COMPILE = 'FAIL_COMPILE';

export const START_EXECUTE = 'START_EXECUTE';
export const FINISH_EXECUTE = 'FINISH_EXECUTE';
export const FAIL_EXECUTE = 'FAIL_EXECUTE';

export const STOP_RUN = 'STOP_RUN';
export const PAUSE_RUN = 'PAUSE_RUN';
export const CLEAR_STATE = 'CLEAR_STATE';

export const CHANGE_SOURCE = 'CHANGE_SOURCE';
export const STORE_SOURCE = 'STORE_SOURCE';
export const STORE_EDITOR_RESULT = 'STORE_EDITOR_RESULT';

export const START_CONNECT_DRIVE = 'START_CONNECT_DRIVE';
export const FINISH_CONNECT_DRIVE = 'FINISH_CONNECT_DRIVE';
export const FAIL_CONNECT_DRIVE = 'FAIL_CONNECT_DRIVE';

export const START_SAVE_DRIVE = 'START_SAVE_DRIVE';
export const FINISH_SAVE_DRIVE = 'FINISH_SAVE_DRIVE';
export const FAIL_SAVE_DRIVE = 'FAIL_SAVE_DRIVE';

export const START_SHARE_DRIVE = 'START_SHARE_DRIVE';
export const FINISH_SHARE_DRIVE = 'FINISH_SHARE_DRIVE';
export const FAIL_SHARE_DRIVE = 'FAIL_SHARE_DRIVE';

export const START_SIGNOUT_DRIVE = 'START_SIGNOUT_DRIVE';
export const FINISH_SIGNOUT_DRIVE = 'FINISH_SIGNOUT_DRIVE';
export const FAIL_SIGNOUT_DRIVE = 'FAIL_SIGNOUT_DRIVE';

export const CHANGE_REPL_CODE =  'CHANGE_REPL_CODE';
export const RECEIVE_REPL_RESULT = 'RECEIVE_REPL_RESULT';

export const EXPAND_MORE_MENU = 'EXPAND_MORE_MENU';
export const COLLAPSE_MORE_MENU = 'COLLAPSE_MORE_MENU';

export const INCREMENT_FONT_SIZE = 'INCREMENT_FONT_SIZE';
export const DECREMENT_FONT_SIZE = 'DECREMENT_FONT_SIZE';

export const CONFIGURE_CODEMIRROR = 'CONFIGURE_CODEMIRROR';
