export const RUNNING = 'RUNNING';

export const START_LOAD_RUNTIME = 'START_LOAD_RUNTIME';
export const FINISH_LOAD_RUNTIME = 'FINISH_LOAD_RUNTIME';
export const FAIL_LOAD_RUNTIME = 'FAIL_LOAD_RUNTIME';
